proxstar/templates/base.html
=> Remove duplicate </body> tag

proxstar/tasks.py
=> only send 1 email for rtp expiration notices

LICENSE.txt, README.md
=> Fix basic Github stuff

proxstar/mail.py
=> Add Date field to notification email

gunicorn_conf.py, proxstar/__init__.py, proxstar/tasks.py, proxstar/vm.py, proxstar/vnc.py
also did a yapf for formatting
=> fix template provisioning by verifying VM is provisioned before doing anything else

proxstar/__init__.py
=> Move url_for import to Flask where it should be

proxstar/__init__.py, proxstar/user.py
For real this time (thanks pycharm)
=> Fix all incorrect imports

config.py, proxstar/__init__.py, requirements.txt
The conditional config has a definition for VERSION which is used in SENTRY_CONFIG. The proxstar config does not have a definition for VERSION so that is not implemented in the SENTRY_CONFIG.
=> Add sentry with integrations

config.py, proxstar/__init__.py, requirements.txt
Things broke, try again next time
=> Revert "Add sentry with integrations"

config.py, proxstar/__init__.py, rqsettings.py
There is a deprecated env value we're getting warnings for
=> Adding redis host config value and adding redis

config.py, gunicorn_conf.py
We keep reaching the timeout of 30 seconds. Especially when it comes to building initial cache, but also in user experience. A page that takes 2 minutes to load but loads is better than one that takes 30 seconds and doesn't
=> Extending gunicorn timeout

proxstar/__init__.py, proxstar/ldapdb.py, requirements.txt
We were not caching ldap in the application, we should do some ldap caching for groups and whether or not someone is a user
=> Simple ldap cache

proxstar/__init__.py, proxstar/ldapdb.py
Reverts ComputerScienceHouse/proxstar#63
=> Revert "Simple ldap cache"

requirements.txt
Updating to newest version of proxmoxer, we're using newest proxmox
=> Updating proxmoxer api

requirements.txt
Reverts ComputerScienceHouse/proxstar#71
=> Revert "Update csh-ldap requirement from ~=2.2.0 to ~=2.3.0"

config.py, proxstar/templates/base.html
=> Adding datadog RUM to Proxstar

proxstar/static/css/styles.css, proxstar/static/js/script.js, proxstar/tasks.py, proxstar/templates/base.html, proxstar/templates/vm_details.html, proxstar/vm.py
Fixes #85 
May need adjustments for mobile devices, possibly remove device description in the selection modal
=> Boot order handling

.pylintrc, proxstar/__init__.py, proxstar/db.py, proxstar/user.py, proxstar/vnc.py, requirements.txt
Proxstar is currently broken, especially with the current set of dependencies. This PR should fix CI and builds
Builds passing on OKD currently
=> Fixing Proxstar for 2022 deps

Dockerfile, requirements.txt
https://app.datadoghq.com/apm/services/proxstar/operations/flask.request/resources?env=prod
Still need to do deployments and stuff (and figure out why she is not reporting when VNC breaks).
=> Update + Enable `ddtrace`

proxstar/db.py
Ceph is bigger now, give people more freedom
=> Increase disk allotment

README.md
=> Add Python Version badge

HACKING/README.md, gunicorn.conf.py, proxstar/__init__.py, proxstar/tasks.py
This does too many things, but I fucked up earlier today so oh well, sorry I suck at computers :)
I've checked this over a whole bunch, did a ton of different shit to a test VM involving the VNC console, and it should actually work.
=> Launch websockify based on config variable, fix more VNC crashes, properly delete keys from Redis using API

proxstar/__init__.py, proxstar/static/js/script.js, proxstar/templates/vm_details.html, proxstar/vm.py
People like adding drives, interfaces, ISOs, all that jazz. Now, instead of asking an RTP, do it yourself!
=> Add more customization options
